"""add password

Revision ID: 37d21003e0aa
Revises: 2b81d7421db9
Create Date: 2023-06-23 22:57:57.046118

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "37d21003e0aa"
down_revision = "2b81d7421db9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
